import { Inter } from "next/font/google";
import "./globals.css";
import Heading from './components/Heading';
import AuthProvider from "./service/AuthProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>
             <Heading/>
        {children}
        <footer>
          <h1>
            This is Footer
          </h1>
        </footer>
        </AuthProvider>

        </body>
    </html>
  );
}
